config/routes.rb
Wysypisko::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]

  match '/signup',     :to => 'users#new'
  match '/signin',     :to => 'sessions#new'
  match '/signout',    :to => 'sessions#destroy'

  match '/register', :to => 'pages#register'
  match '/add', :to => 'pages#add'
  match '/about', :to => 'pages#about'
  match '/top', :to => 'pages#top'
  match '/random', :to => 'pages#random'
  match '/stats', :to => 'pages#stats'
  match '/contact', :to => 'pages#contact'
  
  root :to => 'pages#main'

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "O Autorze", about_path %></li>
      <li><%= link_to "Kontakt", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Glowna", root_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Dodaj", add_path %></li>
      <li><%= link_to "Uzytkownicy", users_path %></li>
      <li><%= link_to "Moje posty", current_user %></li>
      <li><%= link_to "Ustawienia", edit_user_path(current_user) %></li>
      <% end %>
      <li><%= link_to "Top", top_path %></li>
      <li><%= link_to "Losowa", random_path %></li>
      <% if signed_in? %>
        <% if admin? %>
	    <li><%= link_to "Statystki", stats_path %></li>
        <% end %>
      <li><%= link_to "Wyloguj sie", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "Zarejestruj sie", register_path %></li>
      <li><%= link_to "Zaloguj sie", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <% flash.each do |key, value | %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
    <!--  <%= debug(params) if Rails.env.development? %> -->
    </div>
  </body>
</html>